# Generated by Django 2.1.5 on 2022-12-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
