# Generated by Django 2.1.5 on 2022-12-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0002_delete_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Audio Tracks',
            },
        ),
    ]
