# Generated by Django 2.1.5 on 2022-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0005_auto_20221226_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='end_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='start_time',
            field=models.FloatField(),
        ),
    ]
