# Generated by Django 2.1.5 on 2022-12-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0007_auto_20221226_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='chunks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
