# Generated by Django 2.1.5 on 2022-12-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0008_audio_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='chunks',
            field=models.IntegerField(default=0),
        ),
    ]
