# Generated by Django 2.1.5 on 2022-12-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0009_auto_20221226_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='audio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ground_truth.Audio'),
        ),
    ]
