# Generated by Django 2.1.5 on 2022-12-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0014_auto_20221227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
