# Generated by Django 2.1.5 on 2023-01-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0018_remove_audio_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='_selected_image_ids',
            new_name='_selected_ids',
        ),
    ]
