# Generated by Django 2.1.5 on 2023-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0020_audio__ground_truth'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='music',
            field=models.BooleanField(default=True),
        ),
    ]
