# Generated by Django 2.1.5 on 2023-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0021_audio_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='index',
            field=models.IntegerField(blank=True),
        ),
    ]
