# Generated by Django 2.1.5 on 2023-03-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0022_auto_20230203_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name_plural': 'Audio Sources'},
        ),
    ]
