# Generated by Django 2.1.5 on 2022-12-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GroundTruth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='ground_truth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_truth_app.GroundTruth'),
        ),
    ]
