# Generated by Django 2.1.5 on 2022-12-24 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0003_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'verbose_name_plural': 'Chunks'},
        ),
        migrations.RenameField(
            model_name='chunk',
            old_name='duration',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='ground_truth',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='image',
        ),
        migrations.AddField(
            model_name='chunk',
            name='audio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ground_truth.Audio'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='GroundTruth',
        ),
    ]
