# Generated by Django 2.1.5 on 2022-12-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0004_auto_20221224_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='coverart_colour',
            field=models.CharField(default='rgb()', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chunk',
            name='index',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='slug',
            field=models.SlugField(),
        ),
    ]
