# Generated by Django 2.1.5 on 2022-12-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0006_auto_20221226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='_image_ids',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunk',
            name='_selected_image_ids',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
