# Generated by Django 2.1.5 on 2022-12-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0011_auto_20221226_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcript',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
