# Generated by Django 2.1.5 on 2022-12-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0012_audio_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='chunks',
        ),
    ]
