# Generated by Django 2.1.5 on 2022-12-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0013_remove_audio_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
