# Generated by Django 2.1.5 on 2022-12-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0015_auto_20221227_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='artist',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
