# Generated by Django 2.1.5 on 2023-01-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0019_auto_20230117_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='_ground_truth',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
